module Frank.Cli.Core.Tests.AstRenderTests

open Expecto
open Frank.Cli.Core

[<Tests>]
let astRenderTests =
    testList
        "AstRender"
        [ test "formatTypedValueModule emits namespace + nested module + typed record value" {
              let value =
                  AstRender.recordExpr
                      [ "ProfileUri", AstRender.strExpr "/alps/tictactoe"
                        "AlpsDescriptors",
                        AstRender.listExpr
                            [ AstRender.recordExpr
                                  [ "Id", AstRender.strExpr "MoveAction"
                                    "Type", AstRender.strExpr "semantic"
                                    "Doc", AstRender.noneExpr
                                    "Href", AstRender.someStrExpr "https://schema.org/MoveAction" ] ] ]

              let src =
                  AstRender.formatTypedValueModule
                      "TicTacToe.GeneratedDiscovery"
                      [ "Frank.Discovery" ]
                      "discoveryConfig"
                      "DiscoveryConfig"
                      value

              let expected =
                  "namespace TicTacToe\n\nmodule GeneratedDiscovery =\n    open Frank.Discovery\n\n    let discoveryConfig: DiscoveryConfig =\n        { ProfileUri = \"/alps/tictactoe\"\n          AlpsDescriptors =\n            [ { Id = \"MoveAction\"\n                Type = \"semantic\"\n                Doc = None\n                Href = Some \"https://schema.org/MoveAction\" } ] }\n"

              Expect.equal src expected "byte-exact Fantomas-formatted module"
          }

          test "uriExpr renders Uri applied to a string literal" {
              let src =
                  AstRender.formatTypedValueModule "A.B" [] "x" "System.Uri" (AstRender.uriExpr "https://schema.org/X")

              Expect.stringContains src "let x: System.Uri = Uri \"https://schema.org/X\"" "Uri application"
          }

          test "two calls are byte-identical (determinism)" {
              let mk () =
                  AstRender.formatTypedValueModule "A.B" [] "x" "int" (AstRender.strExpr "1")

              Expect.equal (mk ()) (mk ()) "deterministic output"
          }

          test "formatModule emits a DU + two match functions with typeof, byte-exact" {
              let iri =
                  AstRender.matchFunction
                      "iri"
                      "r"
                      "SemanticResource"
                      "System.Uri"
                      [ "Move", AstRender.appExpr "System.Uri" (AstRender.strExpr "https://schema.org/MoveAction")
                        "Game", AstRender.appExpr "System.Uri" (AstRender.strExpr "https://schema.org/Game") ]

              let clr =
                  AstRender.matchFunction
                      "clrType"
                      "r"
                      "SemanticResource"
                      "System.Type"
                      [ "Move", AstRender.rawExpr "typeof<TicTacToe.Move>"
                        "Game", AstRender.rawExpr "typedefof<TicTacToe.Game<_>>" ]

              let du = AstRender.unionDecl "SemanticResource" [ "Move"; "Game" ]

              let src =
                  AstRender.formatModule "TicTacToe.GeneratedSemanticModel" None [] [ du; iri; clr ]

              let expected =
                  "namespace TicTacToe\n\nmodule GeneratedSemanticModel =\n    type SemanticResource =\n        | Move\n        | Game\n\n    let iri (r: SemanticResource) : System.Uri =\n        match r with\n        | Move -> System.Uri \"https://schema.org/MoveAction\"\n        | Game -> System.Uri \"https://schema.org/Game\"\n\n    let clrType (r: SemanticResource) : System.Type =\n        match r with\n        | Move -> typeof<TicTacToe.Move>\n        | Game -> typedefof<TicTacToe.Game<_>>\n"

              Expect.equal src expected "byte-exact DU + match functions"
          }

          test "formatModule prepends a leading comment when provided" {
              let du = AstRender.unionDecl "R" [ "A" ]

              let src =
                  AstRender.formatModule
                      "N.GeneratedSemanticModel"
                      (Some "// <auto-generated> guard </auto-generated>")
                      []
                      [ du ]

              Expect.stringContains src "// <auto-generated> guard </auto-generated>" "comment present"
              Expect.stringContains src "type R =" "DU present after comment"
          }

          test "formatModule renders multiple typed value bindings" {
              let decls =
                  [ AstRender.valueDecl
                        "ontology"
                        "OntologyDecl"
                        (AstRender.recordExpr
                            [ "Classes", AstRender.listExpr []; "ContextBases", AstRender.listExpr [] ])
                    AstRender.valueDecl
                        "graph"
                        "VDS.RDF.IGraph"
                        (AstRender.appExpr "Ontology.toGraph" (AstRender.rawExpr "ontology")) ]

              let src =
                  AstRender.formatModule "T.GeneratedLinkedData" None [ "Frank.Semantic"; "Frank.LinkedData" ] decls

              Expect.stringContains src "let ontology: OntologyDecl =" "typed ontology binding"

              Expect.stringContains
                  src
                  "let graph: VDS.RDF.IGraph = Ontology.toGraph ontology"
                  "graph binding calls interpreter"
          }

          test "tupleAppExpr renders a tupled DU-case application; intExpr/someExpr render" {
              let e =
                  AstRender.tupleAppExpr
                      "RecordShape"
                      [ AstRender.uriExpr "https://schema.org/MoveAction"
                        AstRender.listExpr [ AstRender.intExpr 1; AstRender.someExpr (AstRender.rawExpr "XsdInteger") ] ]

              let src =
                  AstRender.formatModule "T.GeneratedValidation" None [] [ AstRender.valueDecl "x" "ShapeDecl" e ]

              Expect.stringContains src "RecordShape (Uri \"https://schema.org/MoveAction\"," "tupled ctor application"
              Expect.stringContains src "[ 1; Some XsdInteger ]" "int + Some-enum in list"
          } ]
