module Frank.Cli.Core.Tests.AstRenderTests

open Expecto
open Frank.Cli.Core

[<Tests>]
let astRenderTests =
    testList
        "AstRender"
        [ test "formatTypedValueModule emits namespace + nested module + typed record value" {
              let value =
                  AstRender.recordExpr
                      [ "ProfileUri", AstRender.strExpr "/alps/tictactoe"
                        "AlpsDescriptors",
                        AstRender.listExpr
                            [ AstRender.recordExpr
                                  [ "Id", AstRender.strExpr "MoveAction"
                                    "Type", AstRender.strExpr "semantic"
                                    "Doc", AstRender.noneExpr
                                    "Href", AstRender.someStrExpr "https://schema.org/MoveAction" ] ] ]

              let src =
                  AstRender.formatTypedValueModule
                      "TicTacToe.GeneratedDiscovery"
                      None
                      [ "Frank.Discovery" ]
                      "discoveryConfig"
                      "DiscoveryConfig"
                      value

              let expected =
                  "namespace TicTacToe\n\nmodule GeneratedDiscovery =\n    open Frank.Discovery\n\n    let discoveryConfig: DiscoveryConfig =\n        { ProfileUri = \"/alps/tictactoe\"\n          AlpsDescriptors =\n            [ { Id = \"MoveAction\"\n                Type = \"semantic\"\n                Doc = None\n                Href = Some \"https://schema.org/MoveAction\" } ] }\n"

              Expect.equal src expected "byte-exact Fantomas-formatted module"
          }

          test "uriExpr renders Uri applied to a string literal" {
              let src =
                  AstRender.formatTypedValueModule
                      "A.B"
                      None
                      []
                      "x"
                      "System.Uri"
                      (AstRender.uriExpr "https://schema.org/X")

              Expect.stringContains src "let x: System.Uri = Uri \"https://schema.org/X\"" "Uri application"
          }

          test "two calls are byte-identical (determinism)" {
              let mk () =
                  AstRender.formatTypedValueModule "A.B" None [] "x" "int" (AstRender.strExpr "1")

              Expect.equal (mk ()) (mk ()) "deterministic output"
          }

          test "formatModule emits a DU + two match functions with typeof, byte-exact" {
              let iri =
                  AstRender.matchFunction
                      "iri"
                      "r"
                      "SemanticResource"
                      "System.Uri"
                      [ "Move", AstRender.appExpr "System.Uri" (AstRender.strExpr "https://schema.org/MoveAction")
                        "Game", AstRender.appExpr "System.Uri" (AstRender.strExpr "https://schema.org/Game") ]

              let clr =
                  AstRender.matchFunction
                      "clrType"
                      "r"
                      "SemanticResource"
                      "System.Type"
                      [ "Move", AstRender.rawExpr "typeof<TicTacToe.Move>"
                        "Game", AstRender.rawExpr "typedefof<TicTacToe.Game<_>>" ]

              let du = AstRender.unionDecl "SemanticResource" [ "Move"; "Game" ]

              let src =
                  AstRender.formatModule "TicTacToe.GeneratedSemanticModel" None [] [ du; iri; clr ]

              let expected =
                  "namespace TicTacToe\n\nmodule GeneratedSemanticModel =\n    type SemanticResource =\n        | Move\n        | Game\n\n    let iri (r: SemanticResource) : System.Uri =\n        match r with\n        | Move -> System.Uri \"https://schema.org/MoveAction\"\n        | Game -> System.Uri \"https://schema.org/Game\"\n\n    let clrType (r: SemanticResource) : System.Type =\n        match r with\n        | Move -> typeof<TicTacToe.Move>\n        | Game -> typedefof<TicTacToe.Game<_>>\n"

              Expect.equal src expected "byte-exact DU + match functions"
          }

          test "formatModule emits trivia comment as first line via Fabulous.AST (no string concat)" {
              let du = AstRender.unionDecl "R" [ "A" ]

              let src =
                  AstRender.formatModule
                      "N.GeneratedSemanticModel"
                      (Some "<auto-generated> guard </auto-generated>")
                      []
                      [ du ]

              Expect.stringContains src "// <auto-generated> guard </auto-generated>" "comment present"
              Expect.isFalse (src.Contains "// //") "no double-slash (not string concat)"
              Expect.stringContains src "type R =" "DU present after comment"

              let commentIdx = src.IndexOf "// <auto-generated>"
              let typeIdx = src.IndexOf "type R ="
              Expect.isTrue (commentIdx >= 0) "comment line found"
              Expect.isTrue (typeIdx >= 0) "type declaration found"
              Expect.isTrue (commentIdx < typeIdx) "header comment precedes first declaration"
          }

          test "autoGeneratedHeader constant is bare text without leading // " {
              Expect.isFalse (AstRender.autoGeneratedHeader.StartsWith "//") "bare text, no // prefix"
              Expect.stringContains AstRender.autoGeneratedHeader "<auto-generated>" "<auto-generated> marker"
          }

          test "validateModuleName accepts namespace-qualified name" {
              Expect.isOk (AstRender.validateModuleName "A.B") "A.B is valid"
              Expect.isOk (AstRender.validateModuleName "My.Namespace.Module") "multi-segment valid"
          }

          test "validateModuleName rejects whitespace" {
              Expect.isError (AstRender.validateModuleName "") "empty must return Error"
              Expect.isError (AstRender.validateModuleName "   ") "whitespace must return Error"

              match AstRender.validateModuleName "" with
              | Error msg -> Expect.stringContains msg "whitespace" "error mentions whitespace"
              | Ok _ -> failtest "expected Error"
          }

          test "validateModuleName rejects dotless name" {
              Expect.isError (AstRender.validateModuleName "NoDot") "dotless must return Error"

              match AstRender.validateModuleName "NoDot" with
              | Error msg -> Expect.stringContains msg "." "error mentions dot requirement"
              | Ok _ -> failtest "expected Error"
          }

          test "optionExpr None yields noneExpr output" {
              let src =
                  AstRender.formatModule
                      "T.M"
                      None
                      []
                      [ AstRender.valueDecl "x" "int option" (AstRender.optionExpr AstRender.strExpr None) ]

              Expect.stringContains src "= None" "None renders as None"
          }

          test "optionExpr Some yields someExpr output" {
              let src =
                  AstRender.formatModule
                      "T.M"
                      None
                      []
                      [ AstRender.valueDecl "x" "string option" (AstRender.optionExpr AstRender.strExpr (Some "hello")) ]

              Expect.stringContains src "= Some \"hello\"" "Some renders via someExpr"
          }

          test "formatModule renders multiple typed value bindings" {
              let decls =
                  [ AstRender.valueDecl
                        "ontology"
                        "OntologyDecl"
                        (AstRender.recordExpr
                            [ "Classes", AstRender.listExpr []; "ContextBases", AstRender.listExpr [] ])
                    AstRender.valueDecl
                        "graph"
                        "VDS.RDF.IGraph"
                        (AstRender.appExpr "Ontology.toGraph" (AstRender.rawExpr "ontology")) ]

              let src =
                  AstRender.formatModule "T.GeneratedLinkedData" None [ "Frank.Semantic"; "Frank.LinkedData" ] decls

              Expect.stringContains src "let ontology: OntologyDecl =" "typed ontology binding"

              Expect.stringContains
                  src
                  "let graph: VDS.RDF.IGraph = Ontology.toGraph ontology"
                  "graph binding calls interpreter"
          }

          test "tupleAppExpr renders a tupled DU-case application; intExpr/someExpr render" {
              let e =
                  AstRender.tupleAppExpr
                      "RecordShape"
                      [ AstRender.uriExpr "https://schema.org/MoveAction"
                        AstRender.listExpr [ AstRender.intExpr 1; AstRender.someExpr (AstRender.rawExpr "XsdInteger") ] ]

              let src =
                  AstRender.formatModule "T.GeneratedValidation" None [] [ AstRender.valueDecl "x" "ShapeDecl" e ]

              Expect.stringContains src "RecordShape (Uri \"https://schema.org/MoveAction\"," "tupled ctor application"
              Expect.stringContains src "[ 1; Some XsdInteger ]" "int + Some-enum in list"
          } ]
