language: csharp

dotnet: 3.1.100

mono:
  - 5.2.0

install:
  - mozroots --import --sync
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: xenial
      sudo: required

script: 
  - dotnet --info
  - dotnet restore
  - dotnet build --no-restore -c Release
  - dotnet pack --no-restore --no-build -c Release --include-symbols

branches:
  except:
    - gh-pages