/// Fabulous.AST rendering helpers shared by the code-generation emitters
/// (DiscoveryEmitter, LinkedDataEmitter, ValidationEmitter, ProvenanceEmitter,
/// SemanticModelEmitter). Not consumed outside this assembly; narrowed to
/// internal (#392). Tested directly via InternalsVisibleTo.
module internal Frank.Cli.Core.AstRender

open Fabulous.AST
open Fantomas.Core.SyntaxOak
open type Fabulous.AST.Ast

/// Bare text (no leading // ) for the auto-generated header comment.
/// All emitters pass this to formatModule/formatTypedValueModule.
/// SingleLine adds the // prefix; passing text with // yields // //.
val autoGeneratedHeader: string

/// Validate that moduleName is non-whitespace and namespace-qualified (contains a '.').
/// Returns Ok () when valid, Error with a descriptive message otherwise.
val validateModuleName: moduleName: string -> Result<unit, string>

/// A double-quoted string literal: "s"
val strExpr: s: string -> WidgetBuilder<Expr>

/// The bare identifier None
val noneExpr: WidgetBuilder<Expr>

/// Some "<s>"
val someStrExpr: s: string -> WidgetBuilder<Expr>

/// System.Uri applied to a string literal: Uri "<s>"
val uriExpr: s: string -> WidgetBuilder<Expr>

/// A record literal: { name1 = e1; name2 = e2; ... }
val recordExpr: fields: (string * WidgetBuilder<Expr>) list -> WidgetBuilder<Expr>

/// A list literal: [ e1; e2; ... ]
val listExpr: items: WidgetBuilder<Expr> list -> WidgetBuilder<Expr>

/// An array literal: [| e1; e2; ... |]
val arrayExpr: items: WidgetBuilder<Expr> list -> WidgetBuilder<Expr>

/// Render `namespace <ns>` + `module <name> = <opens> let <valueName>: <typeName> = <value>`.
/// Precondition: moduleName contains at least one '.' (RootNamespace-qualified, per the MSBuild targets).
val formatTypedValueModule:
    moduleName: string ->
    leadingComment: string option ->
    opens: string list ->
    valueName: string ->
    typeName: string ->
    value: WidgetBuilder<Expr> ->
        string

/// A verbatim token expression (e.g. "typeof<T>"). Escape hatch for type applications.
val rawExpr: s: string -> WidgetBuilder<Expr>

/// A function application: <func> <arg>, e.g. appExpr "System.Uri" (strExpr "x") → System.Uri "x"
val appExpr: func: string -> arg: WidgetBuilder<Expr> -> WidgetBuilder<Expr>

/// A curried multi-argument function application: <func> <arg1> <arg2> ...,
/// e.g. appExprN "f" [ a; b ] → f a b. Each arg renders as its own token/group — wrap an
/// arg needing its own parens (e.g. `Some x`) in parenExpr before passing it in.
val appExprN: func: string -> args: WidgetBuilder<Expr> list -> WidgetBuilder<Expr>

/// Wraps an expression in parentheses: (<expr>).
val parenExpr: e: WidgetBuilder<Expr> -> WidgetBuilder<Expr>

/// An integer literal expression.
val intExpr: n: int -> WidgetBuilder<Expr>

/// Some <e>
val someExpr: e: WidgetBuilder<Expr> -> WidgetBuilder<Expr>

/// Renders an option value: None → noneExpr, Some x → someExpr (render x).
val optionExpr: render: ('a -> WidgetBuilder<Expr>) -> value: 'a option -> WidgetBuilder<Expr>

/// A bare tuple expression: (a, b, ...)
val tupleExpr: items: WidgetBuilder<Expr> list -> WidgetBuilder<Expr>

/// A tupled discriminated-union case application: Ctor(a, b, ...)
val tupleAppExpr: ctor: string -> args: WidgetBuilder<Expr> list -> WidgetBuilder<Expr>

/// Wrapper so heterogeneous module declarations can be stored in a single list.
[<NoComparison; NoEquality>]
type ModuleDeclItem =
    | UnionDecl of WidgetBuilder<TypeDefnUnionNode>
    | BindingDecl of WidgetBuilder<BindingNode>

/// A discriminated-union type declaration: type <name> = | c1 | c2 ...
val unionDecl: name: string -> cases: string list -> ModuleDeclItem

/// A plain typed value binding as a module declaration: let <name>: <typeName> = <value>
val valueDecl: name: string -> typeName: string -> value: WidgetBuilder<Expr> -> ModuleDeclItem

/// A single-parameter function declaration with an arbitrary body expression:
/// let <name> (<paramName>: <paramType>) : <returnType> = <body>
val funcDecl:
    name: string ->
    paramName: string ->
    paramType: string ->
    returnType: string ->
    body: WidgetBuilder<Expr> ->
        ModuleDeclItem

/// A match expression: match <subject> with | pat -> e ...
val matchExprClauses: subject: string -> clauses: (string * WidgetBuilder<Expr>) list -> WidgetBuilder<Expr>

/// A DU type declaration with instance member properties.
/// Emits member this.Iri: System.Uri and member this.ClrType: System.Type on the union.
/// Replaces bare module-level let iri/let clrType that clash on open.
val unionDeclWithMembers:
    name: string ->
    cases: string list ->
    iriClauses: (string * WidgetBuilder<Expr>) list ->
    clrTypeClauses: (string * WidgetBuilder<Expr>) list ->
        ModuleDeclItem

/// let <name> (<paramName>: <paramType>) : <returnType> = match <paramName> with <clauses>
val matchFunction:
    name: string ->
    paramName: string ->
    paramType: string ->
    returnType: string ->
    clauses: (string * WidgetBuilder<Expr>) list ->
        ModuleDeclItem

/// Render a module with multiple declarations and an optional leading comment.
/// The comment is emitted as Fabulous.AST trivia (not string concat).
/// Precondition: moduleName must be namespace-qualified (contain a '.').
val formatModule:
    moduleName: string -> leadingComment: string option -> opens: string list -> decls: ModuleDeclItem list -> string
