module Frank.Cli.Core.AstRender

open Fabulous.AST
open Fantomas.Core.SyntaxOak
open type Fabulous.AST.Ast

// ── Shared constants ──────────────────────────────────────────────────────────

/// Bare text (no leading // ) for the auto-generated header comment.
/// All emitters pass this to formatModule/formatTypedValueModule.
/// SingleLine adds the // prefix; passing text with // yields // //.
let autoGeneratedHeader: string =
    "<auto-generated> Generated by Frank codegen — regenerate; do not edit. Compiled against the domain: renaming or removing a mapped type breaks the build. </auto-generated>"

// ── Boundary validation ───────────────────────────────────────────────────────

/// Validate that moduleName is non-whitespace and namespace-qualified (contains a '.').
/// Returns Ok () when valid, Error with a descriptive message otherwise.
let validateModuleName (moduleName: string) : Result<unit, string> =
    if System.String.IsNullOrWhiteSpace moduleName then
        Error "moduleName must not be null or whitespace"
    elif moduleName.LastIndexOf '.' < 0 then
        Error "moduleName must be namespace-qualified (contain a '.')"
    else
        Ok()

// ── Expression primitives (all yield WidgetBuilder<Expr>) ─────────────────────

/// A double-quoted string literal: "s"
let strExpr (s: string) : WidgetBuilder<Expr> = ConstantExpr(String s)

/// The bare identifier None
let noneExpr: WidgetBuilder<Expr> = ConstantExpr "None"

/// Some "<s>"
let someStrExpr (s: string) : WidgetBuilder<Expr> = AppExpr("Some", ConstantExpr(String s))

/// System.Uri applied to a string literal: Uri "<s>"
let uriExpr (s: string) : WidgetBuilder<Expr> = AppExpr("Uri", ConstantExpr(String s))

/// A record literal: { name1 = e1; name2 = e2; ... }
let recordExpr (fields: (string * WidgetBuilder<Expr>) list) : WidgetBuilder<Expr> =
    RecordExpr [ for (name, e) in fields -> RecordFieldExpr(name, e) ]

/// A list literal: [ e1; e2; ... ]
let listExpr (items: WidgetBuilder<Expr> list) : WidgetBuilder<Expr> = ListExpr items

/// An array literal: [| e1; e2; ... |]
let arrayExpr (items: WidgetBuilder<Expr> list) : WidgetBuilder<Expr> = ArrayExpr items

// ── Module assembly ───────────────────────────────────────────────────────────

/// Split "A.B.Name" into ("A.B", "Name"); a dotless name becomes ("", name).
let private splitModuleName (moduleName: string) : string * string =
    match moduleName.LastIndexOf '.' with
    | -1 -> "", moduleName
    | i -> moduleName.[.. i - 1], moduleName.[i + 1 ..]

/// Render `namespace <ns>` + `module <name> = <opens> let <valueName>: <typeName> = <value>`.
/// Precondition: moduleName contains at least one '.' (RootNamespace-qualified, per the MSBuild targets).
let formatTypedValueModule
    (moduleName: string)
    (leadingComment: string option)
    (opens: string list)
    (valueName: string)
    (typeName: string)
    (value: WidgetBuilder<Expr>)
    : string =
    match validateModuleName moduleName with
    | Error e -> invalidOp e
    | Ok() -> ()

    let nsName, modName = splitModuleName moduleName

    let valBinding = Value(valueName, value, typeName)

    let valWithTrivia =
        match leadingComment with
        | None -> valBinding
        | Some text -> valBinding.triviaBefore (SingleLine text)

    let oak =
        Oak() {
            Namespace nsName {
                Module modName {
                    for o in opens do
                        Open o

                    valWithTrivia
                }
            }
        }

    oak |> Gen.mkOak |> Gen.run

// ── Union + match-function builders ──────────────────────────────────────────

/// A verbatim token expression (e.g. "typeof<T>"). Escape hatch for type applications.
let rawExpr (s: string) : WidgetBuilder<Expr> = ConstantExpr s

/// A function application: <func> <arg>, e.g. appExpr "System.Uri" (strExpr "x") → System.Uri "x"
let appExpr (func: string) (arg: WidgetBuilder<Expr>) : WidgetBuilder<Expr> = AppExpr(func, arg)

/// Wraps an expression in parentheses: (<expr>).
let parenExpr (e: WidgetBuilder<Expr>) : WidgetBuilder<Expr> = ParenExpr e

/// An integer literal expression.
let intExpr (n: int) : WidgetBuilder<Expr> = ConstantExpr(string n)

/// Some <e>
let someExpr (e: WidgetBuilder<Expr>) : WidgetBuilder<Expr> = AppExpr("Some", e)

/// Renders an option value: None → noneExpr, Some x → someExpr (render x).
let optionExpr (render: 'a -> WidgetBuilder<Expr>) (value: 'a option) : WidgetBuilder<Expr> =
    match value with
    | None -> noneExpr
    | Some x -> someExpr (render x)

/// A tupled discriminated-union case application: Ctor(a, b, ...)
let tupleAppExpr (ctor: string) (args: WidgetBuilder<Expr> list) : WidgetBuilder<Expr> =
    AppExpr(ctor, ParenExpr(TupleExpr args))

/// Wrapper so heterogeneous module declarations can be stored in a single list.
[<NoComparison; NoEquality>]
type ModuleDeclItem =
    | UnionDecl of WidgetBuilder<TypeDefnUnionNode>
    | BindingDecl of WidgetBuilder<BindingNode>

/// A discriminated-union type declaration: type <name> = | c1 | c2 ...
let unionDecl (name: string) (cases: string list) : ModuleDeclItem =
    UnionDecl(
        Union(name) {
            for c in cases do
                UnionCase(c)
        }
    )

/// A plain typed value binding as a module declaration: let <name>: <typeName> = <value>
let valueDecl (name: string) (typeName: string) (value: WidgetBuilder<Expr>) : ModuleDeclItem =
    BindingDecl(Value(name, value, typeName))

/// let <name> (<paramName>: <paramType>) : <returnType> = match <paramName> with <clauses>
let matchFunction
    (name: string)
    (paramName: string)
    (paramType: string)
    (returnType: string)
    (clauses: (string * WidgetBuilder<Expr>) list)
    : ModuleDeclItem =
    let body =
        MatchExpr(paramName, [ for (pat, e) in clauses -> MatchClauseExpr(pat, e) ])

    BindingDecl(Function(name, [ ParenPat(ParameterPat(paramName, paramType)) ], body, returnType))

/// Attach a trivia comment to the first declaration in the list.
/// Empty decls → trivia dropped; emitters always pass ≥1 decl so this is a no-op guard.
let private attachTrivia (text: string) (decls: ModuleDeclItem list) : ModuleDeclItem list =
    match decls with
    | [] -> decls
    | first :: rest ->
        let withTrivia =
            match first with
            | UnionDecl u -> UnionDecl(u.triviaBefore (SingleLine text))
            | BindingDecl b -> BindingDecl(b.triviaBefore (SingleLine text))

        withTrivia :: rest

/// Render a module with multiple declarations and an optional leading comment.
/// The comment is emitted as Fabulous.AST trivia (not string concat).
/// Precondition: moduleName must be namespace-qualified (contain a '.').
let formatModule
    (moduleName: string)
    (leadingComment: string option)
    (opens: string list)
    (decls: ModuleDeclItem list)
    : string =
    match validateModuleName moduleName with
    | Error e -> invalidOp e
    | Ok() -> ()

    let nsName, modName = splitModuleName moduleName

    let finalDecls =
        match leadingComment with
        | None -> decls
        | Some text -> attachTrivia text decls

    let oak =
        Oak() {
            Namespace nsName {
                Module modName {
                    for o in opens do
                        Open o

                    for d in finalDecls do
                        match d with
                        | UnionDecl u -> u
                        | BindingDecl b -> b
                }
            }
        }

    oak |> Gen.mkOak |> Gen.run
