module Frank.Cli.Core.DiscoveryEmitter

open System
open Frank.Semantic
open Frank.Semantic.LockFile

// ── IRI local-name helper ─────────────────────────────────────────────────────

/// Extract the local name from a full IRI (part after last '#' or '/').
let private localName (iri: string) : string =
    let hashIdx = iri.LastIndexOf('#')
    let slashIdx = iri.LastIndexOf('/')
    let idx = max hashIdx slashIdx

    if idx >= 0 && idx < iri.Length - 1 then
        iri.[idx + 1 ..]
    else
        iri

// ── Descriptor builders ───────────────────────────────────────────────────────

type internal ResolvedDescriptor = { Id: string; Href: string option }

/// Resolve the type-level descriptor for one ResolvedResource. Returns None if ClassIri is absent.
let private typeDescriptor (r: ResolvedResource) : ResolvedDescriptor option =
    r.ClassIri
    |> Option.map (fun uri ->
        let href = uri.AbsoluteUri

        { Id = localName href
          Href = Some href })

/// Resolve field descriptors for one resource; skip fields with no Iri.
let private fieldDescriptors (fields: ResolvedField list) : ResolvedDescriptor list =
    fields
    |> List.choose (fun f ->
        f.Iri
        |> Option.map (fun uri ->
            let href = uri.AbsoluteUri

            { Id = localName href
              Href = Some href }))

/// Collect all descriptors from all resources in dependency order: each type then its fields.
let private collectDescriptors (resources: ResolvedResource list) : ResolvedDescriptor list =
    resources
    |> List.collect (fun r ->
        let typeDs = typeDescriptor r |> Option.toList
        let fieldDs = fieldDescriptors r.Fields
        typeDs @ fieldDs)

/// Collect unique `rel="type"` link values for resources that have a ClassIri.
let private collectDescribedByLinks (resources: ResolvedResource list) : string list =
    let folder (seen: Set<string>, acc: string list) (r: ResolvedResource) =
        match r.ClassIri with
        | None -> seen, acc
        | Some uri ->
            let fullIri = uri.AbsoluteUri

            if Set.contains fullIri seen then
                seen, acc
            else
                let link = $"<{fullIri}>; rel=\"type\""
                Set.add fullIri seen, link :: acc

    let _, revLinks = List.fold folder (Set.empty, []) resources
    List.rev revLinks

// ── Pure projection ───────────────────────────────────────────────────────────

/// Pure projection: model → (descriptors, describedBy links). Testable typed output.
let internal projectDiscovery (_profileUri: string) (model: ResolvedModel) : ResolvedDescriptor list * string list =
    collectDescriptors model.Resources, collectDescribedByLinks model.Resources

// ── Source rendering via AstRender (no string concat) ────────────────────────

let private descriptorExpr (d: ResolvedDescriptor) =
    AstRender.recordExpr
        [ "Id", AstRender.strExpr d.Id
          "Type", AstRender.strExpr "semantic"
          "Doc", AstRender.noneExpr
          "Href", AstRender.optionExpr AstRender.strExpr d.Href ]

let private configExpr (profileUri: string) (descriptors: ResolvedDescriptor list) (links: string list) =
    AstRender.recordExpr
        [ "ProfileUri", AstRender.strExpr profileUri
          "HomeRoute", AstRender.strExpr "/"
          "AlpsDescriptors", AstRender.listExpr (descriptors |> List.map descriptorExpr)
          "DescribedByLinks", AstRender.listExpr (links |> List.map AstRender.strExpr) ]

// ── Public API ────────────────────────────────────────────────────────────────

/// Emit a GeneratedDiscovery F# module from a lock file and vocabulary registry.
///
/// moduleName   — the F# module name to emit (e.g. "TicTacToe.GeneratedDiscovery")
/// profileUri   — the ALPS profile route (e.g. "/alps/tictactoe")
/// registry     — the VocabularyRegistry providing prefix→URI mappings
/// lock         — the resolved lock file
///
/// Returns Ok with the F# source string, or Error with a message if any IRI
/// references an unknown prefix.
let emit
    (moduleName: string)
    (profileUri: string)
    (registry: VocabularyRegistry)
    (lock: LockFile)
    : Result<string, string> =
    AstRender.validateModuleName moduleName

    if String.IsNullOrWhiteSpace profileUri then
        invalidArg (nameof profileUri) "profileUri must not be empty"

    match ResolvedModel.build registry lock with
    | Error e -> Error e
    | Ok model ->
        let descriptors, links = projectDiscovery profileUri model
        let value = configExpr profileUri descriptors links

        Ok(
            AstRender.formatTypedValueModule
                moduleName
                (Some AstRender.autoGeneratedHeader)
                [ "Frank.Discovery" ]
                "discoveryConfig"
                "DiscoveryConfig"
                value
        )
