module Frank.Cli.Core.ProvenanceEmitter

open System
open Frank.Semantic
open Frank.Semantic.LockFile

let private provClassName (c: ProvOClass) : string =
    match c with
    | Entity -> "Entity"
    | Activity -> "Activity"
    | Agent -> "Agent"

let private entryExpr (r: ResolvedResource) =
    let cls = provClassName r.ProvClass.Value

    let iri =
        r.ClassIri |> Option.map (fun u -> u.AbsoluteUri) |> Option.defaultValue ""

    AstRender.tupleExpr
        [ AstRender.strExpr r.FSharpType
          AstRender.parenExpr (AstRender.tupleExpr [ AstRender.strExpr cls; AstRender.strExpr iri ]) ]

// For each prov-classed resource, collect host-relative property paths (app-owned fields only)
// and their class namespace so the middleware can emit URI nodes for class-ranged values.
let private projectFieldRanges
    (using: Set<string>)
    (prefixes: Map<string, Uri>)
    (r: ResolvedResource)
    : (string * string) list =
    if r.ProvClass.IsNone then
        []
    else
        r.Fields
        |> List.choose (fun f ->
            match f.Iri with
            | None -> None
            | Some iri when not (EmitterShared.isExternalIri using prefixes iri) ->
                let relPath = iri.AbsolutePath + iri.Fragment

                let classNs =
                    match relPath.LastIndexOf '#' with
                    | -1 -> relPath + "#"
                    | idx -> relPath.[..idx]

                Some(relPath, classNs)
            | _ -> None)

let private pairExpr (k: string) (v: string) =
    AstRender.parenExpr (AstRender.tupleExpr [ AstRender.strExpr k; AstRender.strExpr v ])

let private renderModule
    (moduleName: string)
    (knownNamespaces: string list)
    (classRanges: (string * string) list)
    (declaredPrefixPairs: (string * string) list)
    (resources: ResolvedResource list)
    : string =
    let entries =
        resources |> List.filter (fun r -> r.ProvClass.IsSome) |> List.map entryExpr

    let decls =
        [ AstRender.valueDecl "provClasses" "(string * (string * string)) list" (AstRender.listExpr entries)
          AstRender.valueDecl
              "knownNamespaces"
              "string[]"
              (AstRender.arrayExpr (knownNamespaces |> List.map AstRender.strExpr))
          AstRender.valueDecl
              "propertyClassRanges"
              "(string * string) list"
              (AstRender.listExpr (classRanges |> List.map (fun (p, n) -> pairExpr p n)))
          AstRender.valueDecl
              "declaredPrefixes"
              "(string * string) list"
              (AstRender.listExpr (declaredPrefixPairs |> List.map (fun (p, n) -> pairExpr p n))) ]

    AstRender.formatModule moduleName (Some AstRender.autoGeneratedHeader) [] decls

let private iriHasPrefix (p: string) (iri: string option) : bool =
    iri |> Option.exists (fun s -> s.StartsWith(p))

let private caseUsesPrefix (p: string) (c: CaseMapping) : bool =
    iriHasPrefix p c.Iri
    || List.exists (fun (f: FieldMapping) -> iriHasPrefix p f.Iri) c.Payload

let private shapeUsesPrefix (p: string) (shape: MappingShape) : bool =
    match shape with
    | MappingShape.Record fs -> List.exists (fun (f: FieldMapping) -> iriHasPrefix p f.Iri) fs
    | MappingShape.Union cs -> List.exists (caseUsesPrefix p) cs

let private prefixUsedInMappings (prefix: string) (mappings: Mapping list) : bool =
    let p = prefix + ":"
    List.exists (fun (m: Mapping) -> iriHasPrefix p m.Iri || shapeUsesPrefix p m.Shape) mappings

/// Convert a declared prefix's absolute namespace URI to a host-relative path when the
/// prefix is app-owned (used in at least one mapping IRI and not backed by a vocabulary
/// entry). Vocabulary-backed prefixes and declared-only reference prefixes (not used in
/// any mapping IRI, e.g. external citation vocabularies) keep their absolute URI unchanged.
let private toStoredNs (lock: LockFile) (prefix: string) (absoluteNs: string) : string =
    let isVocab = Map.containsKey prefix lock.Vocabularies

    if isVocab || not (prefixUsedInMappings prefix lock.Mappings) then
        absoluteNs
    else
        let uri = Uri absoluteNs
        uri.AbsolutePath + uri.Fragment

let emit (moduleName: string) (registry: VocabularyRegistry) (lock: LockFile) : Result<string, string> =
    let knownNamespaces = EmitterShared.computeKnownNamespaces registry

    AstRender.validateModuleName moduleName
    |> Result.bind (fun () -> ResolvedModel.build registry lock)
    |> Result.map (fun model ->
        let classRanges =
            model.Resources |> List.collect (projectFieldRanges model.Using model.Prefixes)

        let declaredPrefixPairs =
            lock.DeclaredPrefixes
            |> Map.toList
            |> List.map (fun (prefix, absoluteNs) -> prefix, toStoredNs lock prefix absoluteNs)

        renderModule moduleName knownNamespaces classRanges declaredPrefixPairs model.Resources)
