module Frank.Cli.Core.ProvenanceEmitter

open Frank.Semantic
open Frank.Semantic.LockFile

let private provClassName (c: ProvOClass) : string =
    match c with
    | Entity -> "Entity"
    | Activity -> "Activity"
    | Agent -> "Agent"

let private entryExpr (r: ResolvedResource) =
    let cls = provClassName r.ProvClass.Value

    let iri =
        r.ClassIri |> Option.map (fun u -> u.AbsoluteUri) |> Option.defaultValue ""

    AstRender.tupleExpr
        [ AstRender.strExpr r.FSharpType
          AstRender.parenExpr (AstRender.tupleExpr [ AstRender.strExpr cls; AstRender.strExpr iri ]) ]

let private renderModule
    (moduleName: string)
    (knownNamespaces: string list)
    (resources: ResolvedResource list)
    : string =
    let entries =
        resources |> List.filter (fun r -> r.ProvClass.IsSome) |> List.map entryExpr

    let decls =
        [ AstRender.valueDecl "provClasses" "(string * (string * string)) list" (AstRender.listExpr entries)
          AstRender.valueDecl
              "knownNamespaces"
              "string[]"
              (AstRender.arrayExpr (knownNamespaces |> List.map AstRender.strExpr)) ]

    AstRender.formatModule moduleName (Some AstRender.autoGeneratedHeader) [] decls

let emit (moduleName: string) (registry: VocabularyRegistry) (lock: LockFile) : Result<string, string> =
    let knownNamespaces = EmitterShared.computeKnownNamespaces registry

    AstRender.validateModuleName moduleName
    |> Result.bind (fun () -> ResolvedModel.build registry lock)
    |> Result.map (fun model -> renderModule moduleName knownNamespaces model.Resources)
