module Frank.Cli.Core.ProvenanceEmitter

open System
open Frank.Semantic
open Frank.Semantic.LockFile

let private provClassName (c: ProvOClass) : string =
    match c with
    | Entity -> "Entity"
    | Activity -> "Activity"
    | Agent -> "Agent"

let private entryExpr (r: ResolvedResource) =
    let cls = provClassName r.ProvClass.Value

    let iri =
        r.ClassIri |> Option.map (fun u -> u.AbsoluteUri) |> Option.defaultValue ""

    AstRender.tupleExpr
        [ AstRender.strExpr r.FSharpType
          AstRender.parenExpr (AstRender.tupleExpr [ AstRender.strExpr cls; AstRender.strExpr iri ]) ]

// For each prov-classed resource, collect host-relative property paths (app-owned fields only)
// and their class namespace so the middleware can emit URI nodes for class-ranged values.
let private projectFieldRanges
    (using: Set<string>)
    (prefixes: Map<string, Uri>)
    (r: ResolvedResource)
    : (string * string) list =
    if r.ProvClass.IsNone then
        []
    else
        r.Fields
        |> List.choose (fun f ->
            match f.Iri with
            | None -> None
            | Some iri when not (EmitterShared.isExternalIri using prefixes iri) ->
                let relPath = iri.AbsolutePath + iri.Fragment

                let classNs =
                    match relPath.LastIndexOf '#' with
                    | -1 -> relPath + "#"
                    | idx -> relPath.[..idx]

                Some(relPath, classNs)
            | _ -> None)

let private renderModule
    (moduleName: string)
    (knownNamespaces: string list)
    (classRanges: (string * string) list)
    (resources: ResolvedResource list)
    : string =
    let entries =
        resources |> List.filter (fun r -> r.ProvClass.IsSome) |> List.map entryExpr

    let classRangeExprs =
        classRanges
        |> List.map (fun (prop, ns) ->
            AstRender.parenExpr (AstRender.tupleExpr [ AstRender.strExpr prop; AstRender.strExpr ns ]))

    let decls =
        [ AstRender.valueDecl "provClasses" "(string * (string * string)) list" (AstRender.listExpr entries)
          AstRender.valueDecl
              "knownNamespaces"
              "string[]"
              (AstRender.arrayExpr (knownNamespaces |> List.map AstRender.strExpr))
          AstRender.valueDecl "propertyClassRanges" "(string * string) list" (AstRender.listExpr classRangeExprs) ]

    AstRender.formatModule moduleName (Some AstRender.autoGeneratedHeader) [] decls

let emit (moduleName: string) (registry: VocabularyRegistry) (lock: LockFile) : Result<string, string> =
    let knownNamespaces = EmitterShared.computeKnownNamespaces registry

    AstRender.validateModuleName moduleName
    |> Result.bind (fun () -> ResolvedModel.build registry lock)
    |> Result.map (fun model ->
        let classRanges =
            model.Resources |> List.collect (projectFieldRanges model.Using model.Prefixes)

        renderModule moduleName knownNamespaces classRanges model.Resources)
