module Frank.Cli.Core.SemanticModelEmitter

open System
open Frank.Semantic
open Frank.Semantic.LockFile

// ── Mapped resource tuple ─────────────────────────────────────────────────────

/// A class-mapped resource with its ClassIri already unwrapped.
/// Only resources where ClassIri.IsSome are promoted to this form.
type private MappedResource =
    { LocalName: string
      ClassIri: Uri
      FSharpType: string
      GenericArity: int }

let private toMapped (r: ResolvedResource) : MappedResource option =
    r.ClassIri
    |> Option.map (fun iri ->
        { LocalName = r.LocalName
          ClassIri = iri
          FSharpType = r.FSharpType
          GenericArity = r.GenericArity })

// ── Type expression helpers ───────────────────────────────────────────────────

/// Build the F# type expression for a clrType match arm.
/// GenericArity = 0 → typeof<FSharpType>
/// GenericArity = N → typedefof<BaseType<_,...>> with N underscores (backtick suffix stripped)
let private clrTypeExpr (fsharpType: string) (genericArity: int) : string =
    if genericArity = 0 then
        "typeof<" + fsharpType + ">"
    else
        let baseName =
            match fsharpType.IndexOf('`') with
            | -1 -> fsharpType
            | idx -> fsharpType.[.. idx - 1]

        let underscores = List.replicate genericArity "_" |> String.concat ","
        "typedefof<" + baseName + "<" + underscores + ">>"

// ── Source rendering ──────────────────────────────────────────────────────────

/// Render the SemanticResource DU type declaration.
let private renderDuDecl (resources: MappedResource list) : string =
    let cases =
        resources |> List.map (fun r -> "    | " + r.LocalName) |> String.concat "\n"

    "type SemanticResource =\n" + cases

/// Render the iri function match expression. Returns System.Uri, not string.
let private renderIriMatch (resources: MappedResource list) : string =
    let arms =
        resources
        |> List.map (fun r -> "    | " + r.LocalName + " -> System.Uri(\"" + r.ClassIri.AbsoluteUri + "\")")
        |> String.concat "\n"

    "let iri (r: SemanticResource) : System.Uri =\n    match r with\n" + arms

/// Render the clrType function match expression.
let private renderClrTypeMatch (resources: MappedResource list) : string =
    let arms =
        resources
        |> List.map (fun r -> "    | " + r.LocalName + " -> " + clrTypeExpr r.FSharpType r.GenericArity)
        |> String.concat "\n"

    "let clrType (r: SemanticResource) : System.Type =\n    match r with\n" + arms

/// Assemble the full F# module source string with anti-drift guard header.
let private assembleModule (moduleName: string) (resources: MappedResource list) : string =
    String.concat
        "\n"
        [ "// <auto-generated> Anti-drift guard: compiled WITH the domain so renaming/removing a mapped type breaks the build. Not consumed at runtime. </auto-generated>"
          $"module {moduleName}"
          ""
          renderDuDecl resources
          ""
          renderIriMatch resources
          ""
          renderClrTypeMatch resources
          "" ]

// ── Public API ────────────────────────────────────────────────────────────────

/// Emit a SemanticModel F# module from a vocabulary registry and lock file.
///
/// moduleName — the F# module name to emit (e.g. "TicTacToe.GeneratedSemanticModel")
/// registry   — the VocabularyRegistry providing prefix→URI mappings
/// lock       — the resolved lock file
///
/// Returns Ok with the F# source string, or Error if no class-mapped resources exist
/// or if ResolvedModel.build fails.
let emit (moduleName: string) (registry: VocabularyRegistry) (lock: LockFile) : Result<string, string> =
    if String.IsNullOrWhiteSpace moduleName then
        invalidArg (nameof moduleName) "moduleName must not be empty"

    match ResolvedModel.build registry lock with
    | Error e -> Error e
    | Ok model ->
        let classMapped = model.Resources |> List.choose toMapped

        if classMapped.IsEmpty then
            Error "no class-mapped resources to generate a semantic model"
        else
            Ok(assembleModule moduleName classMapped)
