module Frank.Cli.Core.SemanticModelEmitter

open System
open Frank.Semantic
open Frank.Semantic.LockFile

// ── Mapped resource tuple ─────────────────────────────────────────────────────

/// A class-mapped resource with its ClassIri already unwrapped.
/// Only resources where ClassIri.IsSome are promoted to this form.
type internal MappedResource =
    { LocalName: string
      ClassIri: Uri
      FSharpType: string
      GenericArity: int
      Cases: ResolvedCase list
      UnionCaseCount: int }

let private toMapped (r: ResolvedResource) : MappedResource option =
    r.ClassIri
    |> Option.map (fun iri ->
        { LocalName = r.LocalName
          ClassIri = iri
          FSharpType = r.FSharpType
          GenericArity = r.GenericArity
          Cases = r.Cases
          UnionCaseCount = r.UnionCaseCount })

// ── Type expression helpers ───────────────────────────────────────────────────

/// Build the F# type expression for a clrType match arm.
/// GenericArity = 0 → typeof<FSharpType>
/// GenericArity = N → typedefof<BaseType<_,...>> with N underscores (backtick suffix stripped)
let private clrTypeExpr (fsharpType: string) (genericArity: int) : string =
    if genericArity = 0 then
        "typeof<" + fsharpType + ">"
    else
        let baseName =
            match fsharpType.IndexOf('`') with
            | -1 -> fsharpType
            | idx -> fsharpType.[.. idx - 1]

        let underscores = List.replicate genericArity "_" |> String.concat ","
        "typedefof<" + baseName + "<" + underscores + ">>"

let private camel (s: string) : string =
    if String.IsNullOrEmpty s then
        s
    else
        string (Char.ToLowerInvariant s.[0]) + s.[1..]

// ── AstRender-based builders ──────────────────────────────────────────────────

let internal projectMapped (model: ResolvedModel) : MappedResource list = model.Resources |> List.choose toMapped

let private autoGenComment =
    "// <auto-generated> Anti-drift guard: compiled WITH the domain so renaming/removing a mapped type breaks the build. Not consumed at runtime. </auto-generated>"

let private duDecl (mapped: MappedResource list) =
    AstRender.unionDecl "SemanticResource" (mapped |> List.map (fun m -> m.LocalName))

let private iriFn (mapped: MappedResource list) =
    AstRender.matchFunction
        "iri"
        "r"
        "SemanticResource"
        "System.Uri"
        (mapped
         |> List.map (fun m -> m.LocalName, AstRender.appExpr "System.Uri" (AstRender.strExpr m.ClassIri.AbsoluteUri)))

let private clrTypeFn (mapped: MappedResource list) =
    AstRender.matchFunction
        "clrType"
        "r"
        "SemanticResource"
        "System.Type"
        (mapped
         |> List.map (fun m -> m.LocalName, AstRender.rawExpr (clrTypeExpr m.FSharpType m.GenericArity)))

let private caseFns (mapped: MappedResource list) =
    mapped
    |> List.choose (fun m ->
        if m.Cases.IsEmpty then
            None
        else
            let fnName = camel m.LocalName + "CaseIri"

            let mappedClauses =
                m.Cases
                |> List.map (fun c ->
                    let pat = if c.IsNullary then c.CaseName else c.CaseName + " _"

                    pat,
                    AstRender.appExpr
                        "Some"
                        (AstRender.parenExpr (AstRender.appExpr "System.Uri" (AstRender.strExpr c.Iri.AbsoluteUri))))

            let clauses =
                if m.Cases.Length = m.UnionCaseCount then
                    mappedClauses
                else
                    mappedClauses @ [ "_", AstRender.rawExpr "None" ]

            Some(AstRender.matchFunction fnName "x" m.FSharpType "System.Uri option" clauses))

// ── Public API ────────────────────────────────────────────────────────────────

/// Emit a SemanticModel F# module from a vocabulary registry and lock file.
///
/// moduleName — the F# module name to emit (e.g. "TicTacToe.GeneratedSemanticModel")
/// registry   — the VocabularyRegistry providing prefix→URI mappings
/// lock       — the resolved lock file
///
/// Returns Ok with the F# source string, or Error if no class-mapped resources exist
/// or if ResolvedModel.build fails.
let emit (moduleName: string) (registry: VocabularyRegistry) (lock: LockFile) : Result<string, string> =
    if String.IsNullOrWhiteSpace moduleName then
        invalidArg (nameof moduleName) "moduleName must not be empty"

    match ResolvedModel.build registry lock with
    | Error e -> Error e
    | Ok model ->
        let mapped = projectMapped model

        if mapped.IsEmpty then
            Error "no class-mapped resources to generate a semantic model"
        else
            let decls = duDecl mapped :: iriFn mapped :: clrTypeFn mapped :: caseFns mapped
            Ok(AstRender.formatModule moduleName (Some autoGenComment) [] decls)
