namespace Frank.Cli.MSBuild

open System.IO
open System.Text
open Frank.Semantic

/// Generates GeneratedValidation.fs — a static F# source file with a pre-built ShapesGraph
/// containing SHACL shapes derived from confirmed type/field mappings in the lock file.
type GenerateValidationTask() =
    inherit SemanticGeneratorTask()

    override this.GenerateFiles(lockFile: LockFile) =
        let expand = CurieResolver.expand lockFile.Vocabularies

        let sh = "http://www.w3.org/ns/shacl#"
        let xsd = "http://www.w3.org/2001/XMLSchema#"
        let rdfType = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"

        let confirmedTypes =
            lockFile.Mappings |> List.filter (fun m -> m.Status = Confirmed)

        let sb = StringBuilder()

        sb.AppendLine("// Auto-generated by Frank.Cli.MSBuild — do not edit") |> ignore
        sb.AppendLine("module GeneratedValidation") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open VDS.RDF") |> ignore
        sb.AppendLine("open VDS.RDF.Shacl") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("/// Pre-built ShapesGraph with SHACL shapes for all confirmed type mappings.")
        |> ignore

        sb.AppendLine("let shapesGraph : ShapesGraph =") |> ignore
        sb.AppendLine("    let g = new Graph()") |> ignore

        let emitUriTriple (s: string) (p: string) (o: string) =
            sb.AppendLine(
                $"    g.Assert(Triple(g.CreateUriNode(UriFactory.Create(\"{s}\")), g.CreateUriNode(UriFactory.Create(\"{p}\")), g.CreateUriNode(UriFactory.Create(\"{o}\"))))"
            )
            |> ignore

        let emitLiteralTriple (s: string) (p: string) (lit: string) (dt: string) =
            sb.AppendLine(
                $"    g.Assert(Triple(g.CreateUriNode(UriFactory.Create(\"{s}\")), g.CreateUriNode(UriFactory.Create(\"{p}\")), g.CreateLiteralNode(\"{lit}\", UriFactory.Create(\"{dt}\"))))"
            )
            |> ignore

        let emitIntTriple (s: string) (p: string) (n: int) =
            sb.AppendLine(
                $"    g.Assert(Triple(g.CreateUriNode(UriFactory.Create(\"{s}\")), g.CreateUriNode(UriFactory.Create(\"{p}\")), g.CreateLiteralNode(\"{n}\", UriFactory.Create(\"{xsd}integer\"))))"
            )
            |> ignore

        for tm in confirmedTypes do
            let shapeUri = $"urn:frank:shape:{tm.FsharpType}"
            let targetClassUri = expand tm.Iri

            emitUriTriple shapeUri rdfType $"{sh}NodeShape"
            emitUriTriple shapeUri $"{sh}targetClass" targetClassUri

            let confirmedFields = tm.Fields |> List.filter (fun f -> f.Status = Confirmed)

            for fm in confirmedFields do
                let propShapeUri = $"urn:frank:propshape:{tm.FsharpType}.{fm.Name}"
                let pathUri = expand fm.Iri

                emitUriTriple shapeUri $"{sh}property" propShapeUri
                emitUriTriple propShapeUri $"{sh}path" pathUri
                emitIntTriple propShapeUri $"{sh}minCount" 1
                emitIntTriple propShapeUri $"{sh}maxCount" 1

                match fm.Pattern with
                | Some p -> emitLiteralTriple propShapeUri $"{sh}pattern" p $"{xsd}string"
                | None -> ()

        sb.AppendLine("    ShapesGraph(g)") |> ignore

        let outPath = Path.Combine(this.OutputDirectory, "GeneratedValidation.fs")
        Directory.CreateDirectory(this.OutputDirectory) |> ignore
        File.WriteAllText(outPath, sb.ToString())
