namespace Frank.Cli.MSBuild

open System.IO
open System.Text
open Frank.Semantic

/// Resolves a CURIE like "schema:Order" to a full IRI using the lock file's vocabulary registry.
/// Returns the original string unchanged if it cannot be expanded.
module private CurieResolver =

    let expand (vocabularies: Map<string, VocabularyEntry>) (iri: string) : string =
        let colonIdx = iri.IndexOf(':')

        if colonIdx <= 0 then
            iri
        else
            let prefix = iri.[.. colonIdx - 1]
            let local = iri.[colonIdx + 1 ..]

            match Map.tryFind prefix vocabularies with
            | None -> iri
            | Some entry -> entry.Uri + local

/// Generates GeneratedLinkedData.fs — a static F# source file with a pre-built JSON-LD
/// @context string and IGraph construction code for confirmed type/field mappings.
type GenerateLinkedDataTask() =
    inherit SemanticGeneratorTask()

    override this.GenerateFiles(lockFile: LockFile) =
        let expand = CurieResolver.expand lockFile.Vocabularies

        let confirmedTypes =
            lockFile.Mappings |> List.filter (fun m -> m.Status = Confirmed)

        let contextUris =
            lockFile.Vocabularies
            |> Map.toSeq
            |> Seq.map (fun (_, entry) -> entry.Uri)
            |> Seq.sort
            |> Seq.toList

        let jsonLdContext =
            let uriLiterals =
                contextUris |> List.map (fun u -> $"\\\"{u}\\\"") |> String.concat ", "

            $"{{\"@context\": [{uriLiterals}]}}"

        let sb = StringBuilder()

        sb.AppendLine("// Auto-generated by Frank.Cli.MSBuild — do not edit") |> ignore
        sb.AppendLine("module GeneratedLinkedData") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open VDS.RDF") |> ignore
        sb.AppendLine("open VDS.RDF.Parsing") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("/// JSON-LD @context referencing external vocabularies declared via `using`.")
        |> ignore

        sb.AppendLine($"let jsonLdContext : string = \"\"\"{jsonLdContext}\"\"\"")
        |> ignore

        sb.AppendLine() |> ignore

        sb.AppendLine("/// Pre-built IGraph with type-to-class and field-to-property triples.")
        |> ignore

        sb.AppendLine("let graph : IGraph =") |> ignore
        sb.AppendLine("    let g = new Graph()") |> ignore

        let rdfType = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
        let owlClass = "http://www.w3.org/2002/07/owl#Class"
        let owlEquivClass = "http://www.w3.org/2002/07/owl#equivalentClass"
        let rdfProperty = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
        let rdfsDomain = "http://www.w3.org/2000/01/rdf-schema#domain"
        let owlEquivProp = "http://www.w3.org/2002/07/owl#equivalentProperty"

        let emitTriple (s: string) (p: string) (o: string) =
            sb.AppendLine(
                $"    g.Assert(Triple(g.CreateUriNode(UriFactory.Create(\"{s}\")), g.CreateUriNode(UriFactory.Create(\"{p}\")), g.CreateUriNode(UriFactory.Create(\"{o}\"))))"
            )
            |> ignore

        for tm in confirmedTypes do
            let typeSubj = $"urn:frank:type:{tm.FsharpType}"
            let vocabIri = expand tm.Iri
            emitTriple typeSubj rdfType owlClass
            emitTriple typeSubj owlEquivClass vocabIri

            for fm in tm.Fields |> List.filter (fun f -> f.Status = Confirmed) do
                let fieldSubj = $"urn:frank:property:{tm.FsharpType}.{fm.Name}"
                let fieldIri = expand fm.Iri
                emitTriple fieldSubj rdfType rdfProperty
                emitTriple fieldSubj rdfsDomain typeSubj
                emitTriple fieldSubj owlEquivProp fieldIri

        sb.AppendLine("    g") |> ignore

        let outPath = Path.Combine(this.OutputDirectory, "GeneratedLinkedData.fs")
        Directory.CreateDirectory(this.OutputDirectory) |> ignore
        File.WriteAllText(outPath, sb.ToString())
