namespace Frank.Cli.MSBuild

open System.IO
open System.Text
open Frank.Semantic

/// Generates GeneratedDiscovery.fs — a static F# source file with pre-built ALPS semantic
/// descriptor entries and RFC 8288 Link header values for confirmed type/field mappings.
type GenerateDiscoveryTask() =
    inherit SemanticGeneratorTask()

    override this.GenerateFiles(lockFile: LockFile) =
        let expand = CurieResolver.expand lockFile.Vocabularies

        let confirmedTypes =
            lockFile.Mappings |> List.filter (fun m -> m.Status = Confirmed)

        let sb = StringBuilder()

        sb.AppendLine("// Auto-generated by Frank.Cli.MSBuild — do not edit") |> ignore
        sb.AppendLine("module GeneratedDiscovery") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("/// Pre-built ALPS descriptor entry.") |> ignore

        sb.AppendLine("type AlpsDescriptor = {") |> ignore
        sb.AppendLine("    Id: string") |> ignore
        sb.AppendLine("    Type: string") |> ignore
        sb.AppendLine("    Doc: string option") |> ignore
        sb.AppendLine("    Href: string option") |> ignore
        sb.AppendLine("}") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine(
            "/// ALPS descriptors per F# type full name (confirmed mappings only)."
        )
        |> ignore

        sb.AppendLine("let alpsDescriptors : Map<string, AlpsDescriptor list> =") |> ignore

        let typeEntries =
            confirmedTypes
            |> List.map (fun tm ->
                let typeIri = expand tm.Iri
                let typeDescriptor = $"{{ Id = \"{tm.FsharpType.Split('.') |> Array.last}\"; Type = \"semantic\"; Doc = None; Href = Some \"{typeIri}\" }}"

                let confirmedFields = tm.Fields |> List.filter (fun f -> f.Status = Confirmed)

                let fieldDescriptors =
                    confirmedFields
                    |> List.map (fun fm ->
                        let fieldIri = expand fm.Iri
                        $"{{ Id = \"{fm.Name.ToLowerInvariant()}\"; Type = \"semantic\"; Doc = None; Href = Some \"{fieldIri}\" }}")

                let allDescriptors = typeDescriptor :: fieldDescriptors
                let descriptorList = allDescriptors |> List.map (fun d -> $"                {d}") |> String.concat $"\n                "
                $"        \"{tm.FsharpType}\", [\n                {descriptorList}]")

        if typeEntries.IsEmpty then
            sb.AppendLine("    Map.ofList []") |> ignore
        else
            sb.AppendLine("    Map.ofList [") |> ignore

            for entry in typeEntries do
                sb.AppendLine(entry) |> ignore

            sb.AppendLine("    ]") |> ignore

        sb.AppendLine() |> ignore

        sb.AppendLine("/// RFC 8288 Link header values for \"describedby\" rel per F# type.")
        |> ignore

        sb.AppendLine("let describedByLinks : Map<string, string list> =") |> ignore

        if confirmedTypes.IsEmpty then
            sb.AppendLine("    Map.ofList []") |> ignore
        else
            sb.AppendLine("    Map.ofList [") |> ignore

            for tm in confirmedTypes do
                let typeIri = expand tm.Iri
                sb.AppendLine($"        \"{tm.FsharpType}\", [\"<{typeIri}>; rel=\\\"describedby\\\"\"]")
                |> ignore

            sb.AppendLine("    ]") |> ignore

        let outPath = Path.Combine(this.OutputDirectory, "GeneratedDiscovery.fs")
        Directory.CreateDirectory(this.OutputDirectory) |> ignore
        File.WriteAllText(outPath, sb.ToString())
