namespace Frank.Cli.MSBuild

open System.IO
open System.Text
open Frank.Semantic

/// Generates GeneratedProvenance.fs — a static F# source file with PROV-O class mappings
/// for use by Frank.Provenance at runtime.
///
/// The lock file does not carry ProvClass annotations (those come from the vocabulary CE),
/// so both maps are emitted as Map.empty. The generated file is valid F# and compiles cleanly.
type GenerateProvenanceTask() =
    inherit SemanticGeneratorTask()

    override this.GenerateFiles(_lockFile: LockFile) =
        let sb = StringBuilder()

        sb.AppendLine("// Auto-generated by Frank.Cli.MSBuild — do not edit") |> ignore
        sb.AppendLine("module GeneratedProvenance") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open Frank.Semantic") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("/// PROV-O class for each domain type with a provClass declaration.")
        |> ignore

        sb.AppendLine("let provClasses : Map<string, ProvOClass> = Map.empty") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine("/// Vocabulary IRI for each provClass-mapped type.") |> ignore
        sb.AppendLine("let typeIris : Map<string, string> = Map.empty") |> ignore

        let outPath = Path.Combine(this.OutputDirectory, "GeneratedProvenance.fs")
        Directory.CreateDirectory(this.OutputDirectory) |> ignore
        File.WriteAllText(outPath, sb.ToString())
