// Auto-generated by Frank.Cli.MSBuild — do not edit
module GeneratedProvenance

open Frank.Semantic

/// PROV-O class for each domain type with a provClass declaration.
let provClasses: Map<string, ProvOClass> = Map.empty

/// Vocabulary IRI for each provClass-mapped type.
let typeIris: Map<string, string> = Map.empty
