namespace Frank.LinkedData

open Microsoft.AspNetCore.Builder
open Microsoft.Extensions.DependencyInjection
open VDS.RDF
open Frank.Builder
open Frank.LinkedData.LinkedDataMiddleware

[<AutoOpen>]
module LinkedDataExtensions =

    type WebHostBuilder with

        /// Register linked data middleware with explicit graph and JSON-LD context.
        [<CustomOperation("useLinkedDataWith")>]
        member _.UseLinkedDataWith(spec: WebHostSpec, graph: IGraph, context: string) : WebHostSpec =
            let config =
                { Graph = graph
                  JsonLdContext = context }

            let addServices (services: IServiceCollection) =
                services.AddSingleton<LinkedDataConfig>(config) |> ignore
                spec.Services(services)

            let addMiddleware (app: IApplicationBuilder) =
                let configured = spec.Middleware(app)
                configured.UseMiddleware<LinkedDataMiddleware>()

            { spec with
                Services = addServices
                Middleware = addMiddleware }

        /// Register linked data middleware, auto-loading graph and context from
        /// the entry assembly's GeneratedLinkedData module (generated by Frank.Cli.MSBuild).
        /// Falls back to an empty graph if the module is not present.
        [<CustomOperation("useLinkedData")>]
        member this.UseLinkedData(spec: WebHostSpec) : WebHostSpec =
            let asm = System.Reflection.Assembly.GetEntryAssembly()

            let graph, context =
                if isNull asm then
                    new Graph() :> IGraph, "{}"
                else
                    match asm.GetType("GeneratedLinkedData") with
                    | null -> new Graph() :> IGraph, "{}"
                    | t ->
                        let g =
                            match t.GetProperty("graph") with
                            | null -> new Graph() :> IGraph
                            | p -> p.GetValue(null) :?> IGraph

                        let c =
                            match t.GetProperty("jsonLdContext") with
                            | null -> "{}"
                            | p -> p.GetValue(null) :?> string

                        g, c

            this.UseLinkedDataWith(spec, graph, context)
