// Auto-generated by Frank.Cli.MSBuild — do not edit
module GeneratedValidation

open VDS.RDF
open VDS.RDF.Shacl

/// Pre-built ShapesGraph with SHACL shapes for all confirmed type mappings.
let shapesGraph: ShapesGraph =
    let g = new Graph()

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:shape:MyApp.Order")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/ns/shacl#NodeShape"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:shape:MyApp.Order")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/ns/shacl#targetClass")),
            g.CreateUriNode(UriFactory.Create("https://schema.org/Order"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:shape:MyApp.Order")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/ns/shacl#property")),
            g.CreateUriNode(UriFactory.Create("urn:frank:propshape:MyApp.Order.Total"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:propshape:MyApp.Order.Total")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/ns/shacl#path")),
            g.CreateUriNode(UriFactory.Create("https://schema.org/totalPaymentDue"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:propshape:MyApp.Order.Total")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/ns/shacl#minCount")),
            g.CreateLiteralNode("1", UriFactory.Create("http://www.w3.org/2001/XMLSchema#integer"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:propshape:MyApp.Order.Total")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/ns/shacl#maxCount")),
            g.CreateLiteralNode("1", UriFactory.Create("http://www.w3.org/2001/XMLSchema#integer"))
        )
    )
    |> ignore

    new ShapesGraph(g)
