<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ContentNegotiation.fsi" />
    <Compile Include="ContentNegotiation.fs" />
    <Compile Include="HandlerDefinition.fsi" />
    <Compile Include="HandlerDefinition.fs" />
    <Compile Include="HandlerBuilder.fsi" />
    <Compile Include="HandlerBuilder.fs" />
    <Compile Include="MediaTypeNegotiation.fsi" />
    <Compile Include="MediaTypeNegotiation.fs" />
    <Compile Include="WebLink.fsi" />
    <Compile Include="WebLink.fs" />
    <Compile Include="NegotiateBuilder.fsi" />
    <Compile Include="NegotiateBuilder.fs" />
    <Compile Include="ProducesMatcherPolicy.fsi" />
    <Compile Include="ProducesMatcherPolicy.fs" />
    <Compile Include="ResourceBuilder.fsi" />
    <Compile Include="ResourceBuilder.fs" />
    <Compile Include="WebHostBuilder.fsi" />
    <Compile Include="WebHostBuilder.fs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
