// Auto-generated by Frank.Cli.MSBuild — do not edit
module GeneratedLinkedData

open VDS.RDF

/// JSON-LD @context referencing external vocabularies declared via `using`.
let jsonLdContext: string = """{"@context": ["https://schema.org/"]}"""

/// Pre-built IGraph with type-to-class and field-to-property triples.
let graph: IGraph =
    let g = new Graph()

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:type:MyApp.Order")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/2002/07/owl#Class"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:type:MyApp.Order")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/2002/07/owl#equivalentClass")),
            g.CreateUriNode(UriFactory.Create("https://schema.org/Order"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:property:MyApp.Order.Total")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:property:MyApp.Order.Total")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/2000/01/rdf-schema#domain")),
            g.CreateUriNode(UriFactory.Create("urn:frank:type:MyApp.Order"))
        )
    )
    |> ignore

    g.Assert(
        Triple(
            g.CreateUriNode(UriFactory.Create("urn:frank:property:MyApp.Order.Total")),
            g.CreateUriNode(UriFactory.Create("http://www.w3.org/2002/07/owl#equivalentProperty")),
            g.CreateUriNode(UriFactory.Create("https://schema.org/totalPaymentDue"))
        )
    )
    |> ignore

    g
