<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <AssemblyName>Frank.Alps.Sample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Catalog.fs" />
    <Compile Include="PingPong.fs" />
    <Compile Include="TrafficLight.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Frank/Frank.fsproj" />
    <ProjectReference Include="../../src/Frank.Alps/Frank.Alps.fsproj" />
    <ProjectReference Include="../../src/Frank.Auth/Frank.Auth.fsproj" />
    <ProjectReference Include="../../src/Frank.Rdf/Frank.Rdf.fsproj" />
    <ProjectReference Include="../../src/Frank.Provenance/Frank.Provenance.fsproj" />
  </ItemGroup>

</Project>
