name: CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use dotnet CLI
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            "8.0.x"
            "9.0.x"
      - name: Build
        run: |
          dotnet restore
          dotnet build Frank.sln -c Release --no-restore
      - name: Pack
        run: dotnet pack src/Frank -c Release --no-restore --no-build --include-symbols -o out
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./out
      - name: Push
        if: startsWith( github.ref, 'refs/tags/v' )
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
          SOURCE: "https://api.nuget.org/v3/index.json"
        run: |
          dotnet nuget push out/*.*nupkg --source $SOURCE --api-key $API_KEY
