name: CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use dotnet CLI
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Pack local dependencies
        run: |
          mkdir -p nupkg
          dotnet pack src/Frank.Cli.MSBuild -c Release -o nupkg
      - name: Build
        run: |
          dotnet restore Frank.sln
          dotnet build Frank.sln -c Release --no-restore
      - name: Test
        run: |
          dotnet test test/Frank.Tests
          dotnet test test/Frank.Analyzers.Tests
          dotnet test test/Frank.Auth.Tests
          dotnet test test/Frank.OpenApi.Tests
          dotnet test test/Frank.Datastar.Tests
          dotnet test test/Frank.Cli.Core.Tests
          dotnet test test/Frank.Cli.IntegrationTests
          dotnet test test/Frank.LinkedData.Tests
          dotnet test test/Frank.LinkedData.Sample.Tests
      - name: Pack
        run: |
          dotnet pack src/Frank -c Release --no-restore --include-symbols -o out
          dotnet pack src/Frank.Analyzers -c Release --no-restore --include-symbols -o out
          dotnet pack src/Frank.Auth -c Release --no-restore --include-symbols -o out
          dotnet pack src/Frank.OpenApi -c Release --no-restore --include-symbols -o out
          dotnet pack src/Frank.Datastar -c Release --no-restore --include-symbols -o out
          dotnet pack src/Frank.LinkedData -c Release --no-restore --include-symbols -o out
          dotnet pack src/Frank.Cli.MSBuild -c Release -o out
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./out
      - name: Push
        if: startsWith( github.ref, 'refs/tags/v' )
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
          SOURCE: "https://api.nuget.org/v3/index.json"
        run: |
          dotnet nuget push out/*.*nupkg --source $SOURCE --api-key $API_KEY --skip-duplicate
